<?php

namespace Database\Seeders;

use App\Models\Produk;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProdukSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $produks = [
            [
                'kategori_id' => 1,
                'nama_produk' => 'Original Kies',
                'harga' => 14000.00,
                'stok' => 59,
                'deskripsi' => 'Cookies klasik dengan choco chips manis dan tekstur lembut-renyah.',
                'foto_produk' => 'original-kies.jpg',
                'status' => 'tersedia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 2,
                'nama_produk' => 'Donat Velvet Cheww',
                'harga' => 13000.00,
                'stok' => 70,
                'deskripsi' => 'Donat Red Velvet lembut dengan cita rasa kaya dan creamy.',
                'foto_produk' => '1766328815-velvet-cheww.jpg',
                'status' => 'tersedia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 2,
                'nama_produk' => 'Donat Choco Cheww',
                'harga' => 13000.00,
                'stok' => 75,
                'deskripsi' => 'Donat empuk dilapisi cokelat manis lumer yang sangat lezat.',
                'foto_produk' => '1766328934-choco-cheww.jpg',
                'status' => 'tersedia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 1,
                'nama_produk' => 'Dark Choco Kies',
                'harga' => 14000.00,
                'stok' => 70,
                'deskripsi' => 'Cookies Dark Choco renyah dengan rasa cokelat hitam yang kaya.',
                'foto_produk' => '1766391161-dark-choco-kies.jpg',
                'status' => 'tersedia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 3,
                'nama_produk' => 'Hazelnut Latte',
                'harga' => 17000.00,
                'stok' => 80,
                'deskripsi' => 'Perpaduan espresso, susu creamy, dan aroma hazelnut yang harum menenangkan.',
                'foto_produk' => '1766391299-hazelnut-latte-cheww.jpg',
                'status' => 'tersedia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 3,
                'nama_produk' => 'Iced Latte',
                'harga' => 17000.00,
                'stok' => 78,
                'deskripsi' => 'Kopi smooth dingin dengan susu creamy yang segar dan nikmat.',
                'foto_produk' => '1766391384-iced-latte-cheww.jpg',
                'status' => 'tersedia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 1,
                'nama_produk' => 'Kismis Kies',
                'harga' => 12000.00,
                'stok' => 75,
                'deskripsi' => 'Cookies kismis renyah dengan isian manis untuk camilan santai.',
                'foto_produk' => '1766391465-kismis-kies.jpg',
                'status' => 'tersedia',
                'created_at' => '2025-12-22 01:17:45',
                'updated_at' => '2025-12-22 03:45:28',
            ],
            [
                'kategori_id' => 3,
                'nama_produk' => 'Latte',
                'harga' => 16000.00,
                'stok' => 80,
                'deskripsi' => 'Kopi susu creamy dengan rasa lembut yang seimbang dan ringan.',
                'foto_produk' => '1766391537-latte-cheww.jpg',
                'status' => 'tersedia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 3,
                'nama_produk' => 'Lemon Tea',
                'harga' => 12000.00,
                'stok' => 118,
                'deskripsi' => 'Minuman teh segar dengan perpaduan lemon yang sangat menyegarkan.',
                'foto_produk' => '1766391603-lemon-tea-cheww.jpg',
                'status' => 'tersedia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 1,
                'nama_produk' => 'Matcha Kies',
                'harga' => 14000.00,
                'stok' => 88,
                'deskripsi' => 'Cookies matcha renyah dengan aroma matcha autentik yang sangat harum.',
                'foto_produk' => '1766391658-matcha-kies.jpg',
                'status' => 'tersedia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 3,
                'nama_produk' => 'Matcha Latte',
                'harga' => 17000.00,
                'stok' => 89,
                'deskripsi' => 'Matcha pilihan dengan susu segar menghasilkan rasa autentik dan lembut.',
                'foto_produk' => '1766391724-matcha-latte-cheww.jpg',
                'status' => 'tersedia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 3,
                'nama_produk' => 'Milkshake Choco',
                'harga' => 17000.00,
                'stok' => 80,
                'deskripsi' => 'Milkshake cokelat berkualitas dengan tekstur creamy yang kaya rasa.',
                'foto_produk' => '1766391789-milkshake-choco-cheww.jpg',
                'status' => 'tersedia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 2,
                'nama_produk' => 'Donat Minty Oreo',
                'harga' => 15000.00,
                'stok' => 96,
                'deskripsi' => 'Donat lembut dengan perpaduan rasa mint segar dan tekstur Oreo.',
                'foto_produk' => '1766391848-minty-oreo-cheww.jpg',
                'status' => 'tersedia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 1,
                'nama_produk' => 'Tiramisu Kies',
                'harga' => 14000.00,
                'stok' => 79,
                'deskripsi' => 'Cookies rasa tiramisu kopi dengan sentuhan krim yang sangat elegan.',
                'foto_produk' => '1766391932-tiramisu-kies.jpg',
                'status' => 'tersedia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 1,
                'nama_produk' => 'Red Velvet Kies',
                'harga' => 15000.00,
                'stok' => 98,
                'deskripsi' => 'Cookies Red Velvet bahan pilihan dengan cita rasa mewah lembut.',
                'foto_produk' => '1766392006-velvet-kies.jpg',
                'status' => 'tersedia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 2,
                'nama_produk' => 'Donat Stroberi Cheww',
                'harga' => 14000.00,
                'stok' => 89,
                'deskripsi' => 'Donat empuk rasa stroberi manis segar dengan aroma buah menggoda.',
                'foto_produk' => '1766404280-stroberi-cheww.png',
                'status' => 'tersedia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 1,
                'nama_produk' => 'Stroberi Kies',
                'harga' => 15000.00,
                'stok' => 88,
                'deskripsi' => 'Cookies stroberi renyah lembut dengan rasa manis segar dan aroma menggoda.',
                'foto_produk' => '1766404342-stroberi-kies.png',
                'status' => 'tersedia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 2,
                'nama_produk' => 'Donat Taro',
                'harga' => 14000.00,
                'stok' => 86,
                'deskripsi' => 'Donat taro empuk manis lembut dengan aroma khas menggoda unik.',
                'foto_produk' => '1766404499-taro-cheww.png',
                'status' => 'tersedia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 1,
                'nama_produk' => 'Lotus Biscoff Kies',
                'harga' => 15000.00,
                'stok' => 110,
                'deskripsi' => 'Cookies Lotus Biscoff renyah manis karamel dengan aroma khas menggoda.',
                'foto_produk' => '1766404544-lotus biscoff kies.png',
                'status' => 'tersedia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 1,
                'nama_produk' => 'Cheese Kies',
                'harga' => 15000.00,
                'stok' => 75,
                'deskripsi' => 'Cookies Cheese gurih lembut creamy dengan rasa keju khas menggoda.',
                'foto_produk' => '1766404588-chesee kies.png',
                'status' => 'tersedia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 1,
                'nama_produk' => 'Cinnamon Smores Kies',
                'harga' => 14000.00,
                'stok' => 87,
                'deskripsi' => 'Cookies Cinnamon Smores renyah manis hangat dengan cokelat lumer menggoda.',
                'foto_produk' => '1766404635-cinnamon smores kies.png',
                'status' => 'tersedia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 4,
                'nama_produk' => 'Ori Croissant',
                'harga' => 14000.00,
                'stok' => 87,
                'deskripsi' => 'Croissant butter klasik yang renyah di luar dan lembut berlayer di dalam, dengan taburan gula halus tipis.',
                'foto_produk' => '1767194780-croissant-ori.png',
                'status' => 'tersedia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 4,
                'nama_produk' => 'Stroberi Croissant',
                'harga' => 14000.00,
                'stok' => 80,
                'deskripsi' => 'Croissant dengan glaze stroberi segar berwarna merah muda, topping buah stroberi asli dan remahan stroberi kering.',
                'foto_produk' => '1767194900-croissant-stroberi.png',
                'status' => 'tersedia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 4,
                'nama_produk' => 'Choco Croissant',
                'harga' => 15000.00,
                'stok' => 82,
                'deskripsi' => 'Croissant dengan siraman glaze coklat pekat, taburan bubuk kakao, dan serutan coklat premium.',
                'foto_produk' => '1767196486-croissant-choco.png',
                'status' => 'tersedia',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kategori_id' => 4,
                'nama_produk' => 'Vanilla Fla Croissant',
                'harga' => 15000.00,
                'stok' => 82,
                'deskripsi' => 'Croissant dengan isian fla vanila yang sangat lembut, diberi topping crumble vanila yang renyah.',
                'foto_produk' => '1767196533-croissant-fla-vanila.png',
                'status' => 'tersedia',
                'created_at' => now(),
                'updated_at' => now(),
            ],



        ];

        Produk::insert($produks);
    }
}
